In [1]:
from pytrends.request import TrendReq

pytrends = TrendReq(hl='ko', tz=360)

In [2]:
kw_list=["그날처럼"]
pytrends.build_payload(kw_list, cat=0, timeframe='2018-01-01 2018-02-08', geo='KR', gprop='')

In [3]:
df = pytrends.interest_over_time()
df

            그날처럼  isPartial
date
2018-01-01    25      False
2018-01-02    38      False
2018-01-03    11      False
2018-01-04    38      False
2018-01-05    22      False
2018-01-06    72      False
2018-01-07    36      False
2018-01-08    41      False
2018-01-09    62      False
2018-01-10    48      False
2018-01-11    64      False
2018-01-12    50      False
2018-01-13    49      False
2018-01-14    42      False
2018-01-15    62      False
2018-01-16    31      False
2018-01-17    37      False
2018-01-18    21      False
2018-01-19    72      False
2018-01-20   100      False
2018-01-21    79      False
2018-01-22    53      False
2018-01-23    85      False
2018-01-24    59      False
2018-01-25    49      False
2018-01-26    50      False
2018-01-27    88      False
2018-01-28    74      False
2018-01-29    38      False
2018-01-30    49      False
2018-01-31    49      False
2018-02-01    65      False
2018-02-02    50      False
2018-02-03    68      False
2018-02-04    61      False
2018-02-05    43      False
2018-02-06    49      False
2018-02-07    16      False
2018-02-08    61      False

In [4]:
#df = pytrends.get_historical_interest(kw_list, year_start=2018, month_start=8, day_start=1, hour_start=0, year_end=2018, month_end=11, day_end=2, hour_end=0, cat=0, geo='KR', gprop='', sleep=60)
#df

In [5]:
from matplotlib import pyplot as plt

In [7]:
plt.show(df)

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().