In [2]:
from pytrends.request import TrendReq

pytrends = TrendReq(hl='ko', tz=360)

In [3]:
kw_list=["좋니"]
pytrends.build_payload(kw_list, cat=0, timeframe='2017-06-22 2018-08-22', geo='KR', gprop='')

In [4]:
df = pytrends.interest_over_time()
df

             좋니  isPartial
date
2017-06-25    6      False
2017-07-02    6      False
2017-07-09   10      False
2017-07-16   13      False
2017-07-23   12      False
2017-07-30   13      False
2017-08-06   21      False
2017-08-13   78      False
2017-08-20  100      False
2017-08-27   78      False
2017-09-03   80      False
2017-09-10   76      False
2017-09-17   90      False
2017-09-24   64      False
2017-10-01   65      False
2017-10-08   67      False
2017-10-15   87      False
2017-10-22   55      False
2017-10-29   49      False
2017-11-05   45      False
2017-11-12   50      False
2017-11-19   56      False
2017-11-26   39      False
2017-12-03   47      False
2017-12-10   26      False
2017-12-17   30      False
2017-12-24   37      False
2017-12-31   36      False
2018-01-07   32      False
2018-01-14   24      False
...         ...        ...
2018-01-28   20      False
2018-02-04   25      False
2018-02-11   23      False
2018-02-18   15      False
2018-02-25   19      False
2018-03-04   18      False
2018-03-11   16      False
2018-03-18   16      False
2018-03-25   14      False
2018-04-01   22      False
2018-04-08   12      False
2018-04-15   17      False
2018-04-22   19      False
2018-04-29   10      False
2018-05-06    9      False
2018-05-13    6      False
2018-05-20   10      False
2018-05-27   16      False
2018-06-03   11      False
2018-06-10   11      False
2018-06-17    7      False
2018-06-24    8      False
2018-07-01   11      False
2018-07-08    6      False
2018-07-15    7      False
2018-07-22    8      False
2018-07-29    7      False
2018-08-05    6      False
2018-08-12    5      False
2018-08-19    9      False

[61 rows x 2 columns]

In [5]:
df = pytrends.get_historical_interest(kw_list, year_start=2018, month_start=8, day_start=1, hour_start=0, year_end=2018, month_end=11, day_end=2, hour_end=0, cat=0, geo='KR', gprop='', sleep=60)
df

                      좋니  isPartial
date
2018-08-01 00:00:00   25      False
2018-08-01 01:00:00   11      False
2018-08-01 02:00:00    5      False
2018-08-01 03:00:00   34      False
2018-08-01 04:00:00   35      False
2018-08-01 05:00:00   47      False
2018-08-01 06:00:00   37      False
2018-08-01 07:00:00   27      False
2018-08-01 08:00:00   48      False
2018-08-01 09:00:00   22      False
2018-08-01 10:00:00   23      False
2018-08-01 11:00:00   46      False
2018-08-01 12:00:00   45      False
2018-08-01 13:00:00   56      False
2018-08-01 14:00:00   18      False
2018-08-01 15:00:00   42      False
2018-08-01 16:00:00   58      False
2018-08-01 17:00:00   56      False
2018-08-01 18:00:00  100      False
2018-08-01 19:00:00   80      False
2018-08-01 20:00:00    0      False
2018-08-01 21:00:00    0      False
2018-08-01 22:00:00   27      False
2018-08-01 23:00:00   54      False
2018-08-02 00:00:00   24      False
2018-08-02 01:00:00   45      False
2018-08-02 02:00:00   20      False
2018-08-02 03:00:00   28      False
2018-08-02 04:00:00   18      False
2018-08-02 05:00:00   51      False
...                  ...        ...
2018-10-29 19:00:00  100      False
2018-10-29 20:00:00    0      False
2018-10-29 21:00:00   24      False
2018-10-29 22:00:00    0      False
2018-10-29 23:00:00   32      False
2018-10-30 00:00:00    8      False
2018-10-30 01:00:00   26      False
2018-10-30 02:00:00   46      False
2018-10-30 03:00:00   29      False
2018-10-30 04:00:00   13      False
2018-10-30 05:00:00    6      False
2018-10-30 06:00:00   35      False
2018-10-30 07:00:00   34      False
2018-10-30 08:00:00   32      False
2018-10-30 09:00:00   12      False
2018-10-30 10:00:00   18      False
2018-10-30 11:00:00    6      False
2018-10-30 12:00:00   70      False
2018-10-30 13:00:00   64      False
2018-10-30 14:00:00   12      False
2018-10-30 15:00:00   49      False
2018-10-30 16:00:00   22      False
2018-10-30 17:00:00   34      False
2018-10-30 18:00:00    0      False
2018-10-30 19:00:00    0      False
2018-10-30 20:00:00   33      False
2018-10-30 21:00:00   24      False
2018-10-30 22:00:00   46      False
2018-10-30 23:00:00   11      False
2018-10-31 00:00:00   24      False

[2197 rows x 2 columns]

In [6]:
from matplotlib import pyplot as plt

plt.plot(df['좋니'])

In [7]:
plt.plot(df['닐로'], )

KeyError: '닐로'